# Generated by Django 5.2.5 on 2025-09-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currency',
            new_name='customers',
        ),
    ]
