# Generated by Django 5.2.5 on 2025-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_currency_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=20)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_taxes', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
