# Generated by Django 5.2.5 on 2025-09-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_product_customers_city_customers_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
