# Generated by Django 5.2.5 on 2025-09-05 08:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customers_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
