# Generated by Django 5.2.5 on 2025-09-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customers_credit_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='company_name',
        ),
    ]
