# Generated by Django 5.2.5 on 2025-09-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
