# Generated by Django 5.2.5 on 2025-09-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_vendor_category_vendor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='tag',
        ),
    ]
