# Generated by Django 5.2.5 on 2025-09-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_customers_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense'), ('payment', 'payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_Type', models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('equity', 'equity'), ('income', 'income'), ('expense', 'expense')], max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('description', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
