# Generated by Django 5.2.5 on 2025-09-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_balance_alter_account_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
