# Generated by Django 5.2.5 on 2025-09-09 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_journal_delete_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='name',
            new_name='journal_name',
        ),
        migrations.CreateModel(
            name='journalentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('accounting_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journal')),
            ],
        ),
        migrations.CreateModel(
            name='JournalItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('journalentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journalentry')),
            ],
        ),
    ]
