# Generated by Django 5.2.5 on 2025-09-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_name_journal_journal_name_journalentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
