# Generated by Django 5.2.5 on 2025-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
