# Generated by Django 5.2.5 on 2025-09-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_journal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalitems',
            old_name='Account',
            new_name='account',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('posted', 'posted'), ('Draft', 'Draft')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalitems',
            name='journalentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.journalentry'),
        ),
    ]
