# Generated by Django 5.2.5 on 2025-09-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('posted', 'posted'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
