# Generated by Django 5.2.5 on 2025-09-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_journalentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.customers'),
            preserve_default=False,
        ),
    ]
