# Generated by Django 5.2.5 on 2025-09-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_vendor_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='account.customers'),
        ),
    ]
