# Generated by Django 5.2.5 on 2025-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_vendor_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('job_title', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
