# Generated by Django 5.2.5 on 2025-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_customer_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales', models.BooleanField(default='False')),
                ('purchase', models.BooleanField(default='false')),
                ('product_type', models.CharField(choices=[('GOODS', 'GOODS'), ('service', 'service'), ('combo', 'combo')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
