# Generated by Django 5.2.5 on 2025-09-15 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_Date', models.DateField(default=django.utils.timezone.now)),
                ('Due_Date', models.DateField(blank=True, null=True)),
                ('payments_terms', models.CharField(choices=[('Immediate payment', 'Immediate payment'), ('15 Days', '15 Days'), ('20 Days', '20 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), (' End of following Month', 'End of following Month')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customers')),
                ('journals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journal')),
            ],
        ),
    ]
