# Generated by Django 5.2.5 on 2025-09-15 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('Accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.product')),
            ],
        ),
    ]
