# Generated by Django 5.2.5 on 2025-09-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_invoice_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_lines',
            name='invoices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.invoice'),
            preserve_default=False,
        ),
    ]
