# Generated by Django 5.2.5 on 2025-09-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_invoice_lines_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_lines',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='account.invoice'),
        ),
    ]
