# Generated by Django 5.2.5 on 2025-09-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_invoice_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice_lines',
            new_name='InvoiceLine',
        ),
    ]
