# Generated by Django 5.2.5 on 2025-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_rename_invoice_lines_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Status',
            field=models.CharField(choices=[('posted', 'posted'), ('draft', 'draft'), ('paid', 'paid'), ('cancelled', 'cancelled')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
