# Generated by Django 5.2.5 on 2025-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Status',
            field=models.CharField(choices=[('posted', 'posted'), ('draft', 'draft'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='draft', max_length=20),
        ),
    ]
