# Generated by Django 5.2.5 on 2025-09-17 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.invoice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customers')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journal')),
            ],
        ),
    ]
