# Generated by Django 5.2.5 on 2025-09-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_customer_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_payment',
            old_name='Invoice',
            new_name='invoice',
        ),
        migrations.AddField(
            model_name='customer_payment',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
