# Generated by Django 5.2.5 on 2025-09-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_rename_invoice_customer_payment_invoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_payment',
        ),
    ]
