# Generated by Django 5.2.5 on 2025-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
