# Generated by Django 5.2.5 on 2025-09-18 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_vendor_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_Date', models.DateField(default=django.utils.timezone.now)),
                ('Due_Date', models.DateField(blank=True, null=True)),
                ('payments_terms', models.CharField(choices=[('Immediate payment', 'Immediate payment'), ('15 Days', '15 Days'), ('20 Days', '20 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), (' End of following Month', 'End of following Month')], max_length=30)),
                ('Status', models.CharField(choices=[('posted', 'posted'), ('draft', 'draft'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='draft', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customers')),
                ('journals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journal')),
            ],
        ),
        migrations.CreateModel(
            name='salesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_Date', models.DateField(default=django.utils.timezone.now)),
                ('Due_Date', models.DateField(blank=True, null=True)),
                ('payments_terms', models.CharField(choices=[('Immediate payment', 'Immediate payment'), ('15 Days', '15 Days'), ('20 Days', '20 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), (' End of following Month', 'End of following Month')], max_length=30)),
                ('Status', models.CharField(choices=[('posted', 'posted'), ('draft', 'draft'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='draft', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customers')),
                ('journals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journal')),
            ],
        ),
        migrations.AlterField(
            model_name='customer_payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='account.salesinvoice'),
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
    ]
