# Generated by Django 5.2.5 on 2025-09-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_purchaseinvoice_salesinvoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='purchaseInvoice',
        ),
    ]
