# Generated by Django 5.2.5 on 2025-09-18 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_delete_purchaseinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Purchases', 'Purchases'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Miscellaneous', 'Miscellaneous'), ('General', 'General'), ('Payroll', 'Payroll'), ('Tax', 'Tax')], max_length=20),
        ),
        migrations.CreateModel(
            name='purchaseinvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_Date', models.DateField(default=django.utils.timezone.now)),
                ('Due_Date', models.DateField(blank=True, null=True)),
                ('payments_terms', models.CharField(choices=[('Immediate payment', 'Immediate payment'), ('15 Days', '15 Days'), ('20 Days', '20 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), (' End of following Month', 'End of following Month')], max_length=30)),
                ('Status', models.CharField(choices=[('posted', 'posted'), ('draft', 'draft'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='draft', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('journals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.journal')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor')),
            ],
        ),
    ]
