# Generated by Django 5.2.5 on 2025-09-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_journal_type_purchaseinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='customer',
        ),
    ]
