# Generated by Django 5.2.5 on 2025-09-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_remove_vendor_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='account.purchaseinvoice')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor_product')),
            ],
        ),
    ]
