# Generated by Django 5.2.5 on 2025-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_purchaseinvoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
