# Generated by Django 5.2.5 on 2025-09-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_alter_vendor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoiceline',
            old_name='Accounts',
            new_name='accounts',
        ),
    ]
