# Generated by Django 5.2.5 on 2025-09-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_rename_accounts_purchaseinvoiceline_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceline',
            old_name='products',
            new_name='Product',
        ),
    ]
