# Generated by Django 5.2.5 on 2025-09-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_rename_products_invoiceline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='Accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.product'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='account.salesinvoice'),
        ),
    ]
